### ISSUE TITLE
Packagers Wanted

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#440]
We currently need packagers. If you want an up to date version of Pithos for your distro of choice then roll up your sleeves and get involved. Become a Pithos packager. This specifically applies to Ubuntu. The Pithos PPA is basically dead and will not be updated unless someone steps up.

**Comment by JasonLG1979** [comment]
We have a packager for Ubuntu. Andrew from http://www.webupd8.org has agreed to maintain the Pithos PPA.

**Comment by ShapeShifter499** [comment]
@TingPing already seems to keep up Arch Linux support through the AUR. 

Thank you for the support @TingPing !

**Comment by JasonLG1979** [comment]
Fedora manages to keep up pretty well also. They have 1.2.1 in the repo for Fedora 25. Ubuntu was the big one. Ubuntu accounts for a lot of our users and they're also the least likely to want to or be able to build from source.

**Comment by TingPing** [comment]
> Fedora manages to keep up pretty well also.

That is me too :P

**Comment by JasonLG1979** [comment]
> That is me too :P

Well where's 1.3.0 then slacker? lol!!!

**Comment by JasonLG1979** [comment]
In the meantime TingPing can you copy those packages that @hotice built to the Pithos PPA in that link I emailed you?

**Comment by JasonLG1979** [comment]
@TingPing I'd like to get 1.3.0 in the press and in the hands of some Ubuntu users so I can shake out as many bugs as possible and release 1.3.1. Ubuntu 17.04 drops in 2 days.

**Comment by TingPing** [comment]
> In the meantime @TingPing can you copy those packages that @hotice built to the Pithos PPA in that link I emailed you?


> Copied from: test. Copied by: TingPing Target series: Xenial
pithos 1.3.0-1ppa1~xenial1 in xenial (pithos_1.3.0.orig.tar.xz already exists in destination archive with different contents.

We would have to rename the source file to upload it.

**Comment by JasonLG1979** [comment]
I had no problem copying it to my PPA? Could you not just delete the conflicting file before you paste the new on in?

**Comment by TingPing** [comment]
AFAICT it is not possible to delete previous sources.

**Comment by JasonLG1979** [comment]
> AFAICT it is not possible to delete previous sources.

Well that's just stupid...

**Comment by TingPing** [comment]
Well, I can get it from a security and reproducability standpoint. Sources are write only.

**Comment by JasonLG1979** [comment]
I can delete packages/sources in my PPA. Maybe you don't have the privileges.

**Comment by TingPing** [comment]
You can delete *packages* you cannot delete *sources*.

**Comment by JasonLG1979** [comment]
![screenshot from 2017-04-11 11-29-32](https://cloud.githubusercontent.com/assets/6667703/24919757/4f7c1e78-1eaa-11e7-9647-aa28e371d7ec.png)

**Comment by JasonLG1979** [comment]
I had no problem deleting the existing packages and re-adding them.

**Comment by hotice** [comment]
Why was the source different? Anyway, a workaround for this is to change the packaging to use "native" source. Using this, the package doesn't use an .orig.tar.xz archive so it should work. I uploaded packages with "native" source to a different test PPA. You can copy the packages from here: https://launchpad.net/~nilarimogard/+archive/ubuntu/test2/+copy-packages?field.name_filter=pithos&field.status_filter=published&field.series_filter=

**Comment by TingPing** [comment]
@hotice Worked, thanks!

**Comment by probonopd** [comment]
If someone makes a ppa for trusty or earlier, then I could easily turn it into an AppImage. Alternatively, we could use Travis CI to do continuous builds and use these to make AppImages.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

**Comment by JasonLG1979** [comment]
The Gtk/Glib versions in Trusty are too for Pithos 1.3.0. I don't even think you can get 1.2.0 working on Trusty. Pithos requires at least Gtk 3.16 preferably at least 3.18 just to be safe. I'm not 100% sure about the min version of Glib. Basically we don't target anything older than the latest Ubuntu LTS.

**Comment by JasonLG1979** [comment]
*to old for Pithos

**Comment by probonopd** [comment]
@JasonLG1979 Ubuntu trusty is still supported... so if you want to target all Ubuntu users you should build against that...

**Comment by TingPing** [comment]
I have no interest in AppImage, we use Flatpak for portable installs. AFAIK nobody has an up to date Flatpak build for 14.04 which is a shame but its not like AppImage can work on 100% of platforms either.

**Comment by probonopd** [comment]
> I have no interest in AppImage, we use Flatpak for portable installs.

Flatpak is cool but portable it is not - have you ever tried to run a Flatpak'd app from a live CD?

> its not like AppImage can work on 100% of platforms either

AppImage can run almost everywhere __if__ you put binaries inside that are compiled on a system no newer than the systems you are targeting.

**Comment by TingPing** [comment]
Yes yes you always talk about live CDs, I genuinely don't care about that.

Look, AppImage by definition cannot be portable, it builds in system libraries and components. You know this.

**Comment by probonopd** [comment]
> Yes yes you always talk about live CDs, I genuinely don't care about that.

Looks we have another definition of "portable" then. Mine is: I can put a portable application on a Live USB stick and take it with me, along with the operating system which I also put on a Live USB stick.

> Look, AppImage by definition cannot be portable, it pulls in system libraries and components. You know this.

Wrong: Most AppImages assume that certain basic libraries (such as glibc) are part of each targeted base system (distribution). Just like you would assume that certain libraries come with Windows and macOS. Of course, it is up to the person who puts together an AppImage to decide which systems to target, and hence, what to bundle (and what to take from the target system). As long as you build on CentOS 6, you can be reasonably safe to assume that most Linux users should be able to run your AppImage. Similar to if you build on Windows 7, you can reasonably assume that most Windows users will be able to run your application at this point.

**Comment by TingPing** [comment]
> As long as you build on CentOS 6, you can be reasonably safe to assume that most Linux users should be able to run your AppImage. 

Right that has obvious problems:

- Your software has to target ancient libs
- You have to hope that many of the system libs you depend upon never break ABI
- Your users still have to have some of those system libs installed

Flatpak and snap bundling a base image solve all of those.

**Comment by probonopd** [comment]
> Your software has to target ancient libs

Your software has to do nothing. You could decide to ship newer versions of libraries if you really must. Just, for basic stuff such as glibc or GTK, it would be considered bloated by many.

> You have to hope that many of the system libs you depend upon never break ABI

You don't need to hope. You file a bug report on libraries that break ABI.

> Your users still have to have some of those system libs installed

Yes, which in the case of glibc and GTK they should have anyway, right?

**Comment by TingPing** [comment]
> You don't need to hope. You file a bug report on libraries that break ABI.

It is too late at that point.

> You could decide to ship newer versions of libraries if you really must. 

Correct me if I am wrong, GObject is in your default blacklist, meaning use system versions?

**Comment by probonopd** [comment]
I have not claimed that my default blacklist is perfect. Yes, I assumed that stuff like glibc, GTK, GNOME, G* is present on each system that _my_ AppImages target (you may decide differently for yours). And I expect from these that they only _add_ stuff, but not _break or remove_ stuff (if they do, then I should remove them from the blacklist or make them fix it).

**Comment by TingPing** [comment]
So its impossible for most applications using modern libraries to bundle their dependencies if gobject is from the system.

I agree with the thought that to be truely portable you cannot rely the system at all.

**Comment by probonopd** [comment]
> So its impossible for most applications using modern libraries to bundle their dependencies if gobject is from the system

@TingPing I don't understand this comment, most likely because I don't know enough about gobject. I am interested in learning about the reasons for your statement but don't want to hijack this thread any further. Maybe you'd like to explain in a [separate GitHub issue](https://github.com/probonopd/AppImages/issues)?

**Comment by JasonLG1979** [comment]
We don't target all Ubuntu users. We don't really specifically target any distro. We just would generally like it if Most Ubuntu users could use the latest Version. Doing our best to make sure the latest version will run on the latest LTS achieves that. We will not be held back by a 3 year old release with ancient libs. Debian stable is more up to date for Pete's sake. As far as appimage vs flatpak vs snap I have educated opinion to offer.

**Comment by JasonLG1979** [comment]
*have no educated opinion

**Comment by JasonLG1979** [comment]
@TingPing can we nail down at least the minimum version for Gtk/GLib so we don't have to have this argument with anyone else? As far as Gtk as I said 3.16 or 3.18 seems to be safe. But really moving forward since 3.18 is the version in the latest Ubuntu LTS I'd say we should target 3.18 as our minimum version of Gtk. I don't know about GLib maybe just target the version that comes with the latest Ubuntu LTS again?

**Comment by TingPing** [comment]
Would require somebody testing it, the code checks for Gtk 3.14 which maps to GLib 2.42 at a glance.

**Comment by JasonLG1979** [comment]
> Would require somebody testing it, the code checks for Gtk 3.14 which maps to GLib 2.42 at a glance.
> 
> We know the GDBus bits require a newer version but that is somewhat optional.

We want a fully functional app plugins and all. 3.18 definitely gets us that.

**Comment by JasonLG1979** [comment]
I'll set up a Debian stable VM and see what happens. Debian stable comes with 3.14 but like you said a few of the plugins will fail without a doubt.

**Comment by JasonLG1979** [comment]
Nope. Debian Stable with Gtk 3.14 and GLib ? will build and install but crashes and burns with this traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pithos/application.py", line 157, in do_command_line
    self.do_activate()
  File "/usr/local/lib/python3.4/site-packages/pithos/application.py", line 170, in do_activate
    self.window = PithosWindow(self, self.test_mode)
  File "/usr/local/lib/python3.4/site-packages/pithos/pithos.py", line 257, in __init__
    load_plugins(self)
  File "/usr/local/lib/python3.4/site-packages/pithos/plugin.py", line 101, in load_plugins
    in_tree_plugins = settings.props.settings_schema.list_children()
AttributeError: 'SettingsSchema' object has no attribute 'list_children'
```

**Comment by TingPing** [comment]
That was added in GLib 2.44 which maps to Gtk 3.16.

**Comment by JasonLG1979** [comment]
Are there any supported distros that use 3.16?

**Comment by JasonLG1979** [comment]
I still say we should just list the minimum as 3.18 and call it a day. I know everything works with 3.18.

**Comment by JasonLG1979** [comment]
> OpenSUSE Leap 42.1 is supported for one more month :P
> 
> Gtk 3.18 + GLib 2.46 sounds fine.

Good deal. I'll update the wiki and my 1st comment in this issue to reflect that.

**Comment by hotice** [comment]
I'm still not in the Pithos Developers Launchpad team so I can't update the PPA for now. You can copy the latest Pithos 1.3.1 to the PPA from here: https://launchpad.net/~nilarimogard/+archive/ubuntu/test/+copy-packages?field.name_filter=pithos&field.status_filter=published&field.series_filter=

**Comment by MggMuggins** [comment]
I wonder what would be required to get Pithos in the Manjaro community repo. The AUR already has the PKGBUILD, but it would be convenient to have in the official. When you mentioned Arch up at the top, do you mean as a part of Community, or just in the AUR?

**Comment by TingPing** [comment]
@MggMuggins Ideally find an Arch TU to pull it in and Manjaro will probably sync that at some point

**Comment by hotice** [comment]
I packaged Pithos 1.4.0 in my test PPA: https://launchpad.net/~nilarimogard/+archive/ubuntu/test/+copy-packages?field.name_filter=pithos&field.status_filter=published&field.series_filter= You can copy it to the Pithos PPA from there.

**Comment by TingPing** [comment]
@hotice Done, thanks!

**Comment by TingPing** [comment]
@brandex007 https://github.com/pithos/pithos/wiki/Installing-from-Source

**Comment by austin6598** [comment]
Has anyone packaged 1.4.1 for ubuntu?

**Comment by TingPing** [comment]
Not that I know of, the Flatpak is the recommended way to get the latest version: https://beta.flathub.org/apps/details/io.github.Pithos

**Comment by silvernode** [comment]
@TingPing The flatpak is what I am using and it works fine most of the time (I think the pandora service hiccups which causes occasional buffering during playback). Is the flatpak the official project package method?

**Comment by TingPing** [comment]
@silvernode Yes.

**Comment by kai4785** [comment]
Here's a CentOS 7 one that depends on packages from epel.

https://gist.github.com/kai4785/4c7e86d92470778298d6a3ac9fb05683

**Comment by TingPing** [comment]
Can also use Flatpaks from RHEL7: https://copr.fedorainfracloud.org/coprs/amigadave/flatpak-epel7/
