### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)

### ISSUE THREAD

**Issue by ShapeShifter499** [pithos/pithos#251]
Hi, 

Today I started to get the error as stated in the title, the full log is below. Any ideas? Maybe Pandora changed something?

Regards, Lance

```
[raansu@Y40-80 ~]$ pithos
sys:1: PyGIWarning: GstPbutils was imported without specifying a version first. Use gi.require_version('GstPbutils', '1.0') before import to ensure that the right version gets loaded.
sys:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
/usr/lib/python3.5/site-packages/pithos/pithos.py:1119: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  self.window = NewPithosWindow(self, self.options)
ERROR - pandora:json_call:127 - Network error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)>
ERROR - pandora:json_call:127 - Network error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)>
ERROR - pandora:json_call:127 - Network error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)>
[raansu@Y40-80 ~]$ 
```

**Comment by ShapeShifter499** [comment]
More logs
```
[raansu@Y40-80 Downloads]$ pithos -vv
sys:1: PyGIWarning: GstPbutils was imported without specifying a version first. Use gi.require_version('GstPbutils', '1.0') before import to ensure that the right version gets loaded.
sys:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
INFO - pithos:do_activate:1118 - Pithos 1.1.1
INFO - plugin:enable:38 - Enabling module mediakeys
INFO - mediakeys:bind_keybinder:71 - Bound media keys with keybinder
INFO - plugin:enable:38 - Enabling module mpris
INFO - plugin:enable:38 - Enabling module lastfm
/usr/lib/python3.5/site-packages/pithos/pithos.py:1119: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  self.window = NewPithosWindow(self, self.options)
INFO - notify:prepare_notify:73 - Notify supports actions
INFO - plugin:enable:38 - Enabling module notify
INFO - plugin:enable:38 - Enabling module notification_icon
DEBUG - pandora:json_call:113 - https://internal-tuner.pandora.com/services/json/?method=auth.partnerLogin
DEBUG - pandora:json_call:114 - b'{"version": "5", "password": "<REDACTED>", "deviceModel": "D01", "username": "pandora one"}'
ERROR - pandora:json_call:127 - Network error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)>
INFO - pithos:error_dialog:584 - Manual retry
DEBUG - pandora:json_call:113 - https://internal-tuner.pandora.com/services/json/?method=auth.partnerLogin
DEBUG - pandora:json_call:114 - b'{"version": "5", "password": "<REDACTED>", "deviceModel": "D01", "username": "pandora one"}'
ERROR - pandora:json_call:127 - Network error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)>
```

**Comment by TingPing** [comment]
So it looks like Pandora changed the certificate for *internal-tuner.pandora.com* to something that is not valid. A work around for now is to disable Pandora One as the normal account uses *tuner.pandora.com* which is valid still.

You can use `openssl s_client -connect internal-tuner.pandora.com:443` to see where it fails, looks like the internal one is self-signed and the public one uses Verisign.

Disabling validation of the cert is possible though that opens us up to MITM. The only other option is to hardcode the fingerprint of their self-signed cert. The problem with that is obviously that it could change at any time and we can't easily update it.

**Comment by JasonLG1979** [comment]
> Disabling validation of the cert is possible though that opens us up to MITM.

On that note as per:
http://stackoverflow.com/questions/27835619/ssl-certificate-verify-failed-error

You can disable Disabling validation of the cert by adding this at the top of Pandora.py by the rest of the imports and rebuilding.
```python
import ssl

ssl._create_default_https_context = ssl._create_unverified_context
```
But like @TingPing said it creates a security issue. So do so at your own risk.

**Comment by JasonLG1979** [comment]
A possible fix and an alternative to hardcoding the cert is to host the cert on github(either in the Pithos project or elsewhere) and have Pithos update the cert in the event of such error. It's trivial to write the cert in the users ./cache folder somewhere.

**Comment by TingPing** [comment]
> pandora_one_cert = ssl.get_server_certificate(('internal-tuner.pandora.com', 443))

If you download a cert over an insecure connection.. well that defeats the point. Yes we could certainly host at least the fingerprint ourself.

**Comment by JasonLG1979** [comment]
> If you download a cert over an insecure connection.. well that defeats the point.
Don't really have much of a choice if it's self signed. No less secure then openssl s_client -connect internal-tuner.pandora.com:443 to get the cert.

**Comment by TingPing** [comment]
@JasonLG1979 I see what you mean, yes clients could just trust the first cert they see but if they change it again then we are back to square one, if Pithos had a trust list we are ofc still just trusting the first thing we see but at least we can handle changes.

**Comment by JasonLG1979** [comment]
```python
HOME = os.path.expanduser('~')
CACHE_FILES_DIR_PATH = '%s/.cache/Pandora-one-cert'%HOME
CERT_FILE_PATH = ''.join((CACHE_FILES_DIR_PATH, '/cert'))

if not os.path.exists(CACHE_FILES_DIR_PATH):
    os.makedirs(CACHE_FILES_DIR_PATH)
    logging.info('%s does not exist, creating it', CACHE_FILES_DIR_PATH)

PANDORA_ONE_SSL_CERT = ssl.get_server_certificate(('internal-tuner.pandora.com', 443))

with open(CERT_FILE_PATH, 'w') as cert_file:
    cert_file.write(PANDORA_ONE_SSL_CERT)
```
Will save the cert to a file It's just a matter of figuring out how to get Pithos to use that saved cert. Playing with ssl context at the moment.

**Comment by ShapeShifter499** [comment]
How does the normal pandora website fetch the higher quality pandora one audio? Maybe we could adapt that?

**Comment by TingPing** [comment]
@ShapeShifter499 I haven't ever looked into but I imagine that everything the website does is private, unlike mobile applications that store keys locally and directly talk with their JSON api the website is probably just a portal in.

**Comment by JasonLG1979** [comment]
The Plex Pandora "Channel" only works with a Pandora One account. I'll see if I can see what it's doing.
https://github.com/plexinc-plugins/Pandora.bundle/tree/master/Contents/Code

**Comment by mintster** [comment]
I don't know if this helps, but while my Pithos 1.1.1 player (on Ubuntu 15.10) is down with the Certificate issue, my Pithos 1.0.3 player (on Linux Mint 17.2) appears unaffected and is working great.

**Comment by ClashTheBunny** [comment]
In other pandora clients, they expose the certificate fingerprint as a configuration option and then post news about new certificates:
[pianod](http://deviousfish.com/pianod/)
> 6 November 2015—The PandoraOne TLS certificate changed recently. If you are using Pandora One, update the value in the ‘set tls fingerprint’ line in your startscript to 7F2BFD338D08D6F952D215C0FC8C3C4C1DC1772F.

or in [pianobar](https://github.com/PromyLOPh/pianobar/issues/554):
> Add this line to your config file (or replace existing): tls_fingerprint = 7F2BFD338D08D6F952D215C0FC8C3C4C1DC1772F

With a fetch script [here](https://github.com/PromyLOPh/pianobar/blob/master/contrib/tls_fingerprint.sh).

But @PromyLOPh says that it's not an issue in HEAD because they are now using curl's cert validation, so I don't know if it's just ignoring certificates now.

I also feel, like @mintster, like I got this error in a rolling fashion.  I feel like it came with an update to wily, but that doesn't make a ton of sense.  It's not that openssl or nss got updated to ban SHA1 certificate hashes or something like that?  I use Pandoki, which derived it's code from pithos, and it worked on one machine longer than it worked on another.

**Comment by TingPing** [comment]
> But @PromyLOPh says that it's not an issue in HEAD because they are now using curl's cert validation, so I don't know if it's just ignoring certificates now.

Must be, it is a self signed cert so no system trusts it by default.

> In other pandora clients, they expose the certificate fingerprint as a configuration option and then post news about new certificates

Adding a configuration option is one option, maybe as a manual override though as I'd rather it work out of the box.

>  it worked on one machine longer than it worked on another.

First thing I would guess is DNS cache maybe? I don't think any change internal to Pithos would have mattered.

**Comment by glennimoss** [comment]
The cert for internal-tuner.pandora.com is not self-signed:
```
$ openssl s_client -connect internal-tuner.pandora.com:443
# ... snip ...
Certificate chain
 0 s:/C=US/ST=California/L=Oakland/O=Pandora Media, Inc./OU=operations/CN=internal-tuner.pandora.com
   i:/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=Terms of use at https://www.verisign.com/rpa (c)10/CN=VeriSign Class 3 International Server CA - G3
# ... snip ...
```

The issuer "VeriSign Class 3 International Server CA" is not in my system-level CA store. (Ubuntu 15.04)
However, the real issue here is what I would consider a misconfiguration of their server. If you run `openssl s_client -connect tuner.pandora.com:443 -showcerts` You will see it list 3 distinct certificates. That is each certificate in the trust chain down to the root VeriSign cert, which is contained in the system CA store. Now running `openssl s_client -connect internal-tuner.pandora.com:443 -showcerts` You will see that it lists exactly 1 certificate. The internal-tuner server should also be sending the entire cert chain. If it did, we wouldn't have any problems. Their cert is properly signed by a trusted authority, however the system has no way of knowing how to link it back to some known root authority. The server is supposed to show you how to get there.

Of course, none of this really helps us DO anything about it :P

**Comment by SebastianHD** [comment]
I can confirm with @ClashTheBunny, I started not being able to connect right after updating from Ubuntu 15.04 to 15.10. Although mine is sl.c:600 error. I know that is of little help. Is this somehow related to python?

**Comment by JasonLG1979** [comment]
Like I said earlier, I'm by no means and expert... So a couple(maybe stupid) questions?

1. Pithos uses blowfish to communicated with Pandora, correct? How much is sent encrypted and how in the clear?
2. If we use TLS fingerprints what is the real risk? How much info would leak if the fingerprint was impersonated.(MITM)?

TLS fingerprints seem to be a bit of a security risk. I was just wondering what the "real world" risk is. Am I correct in assuming that unless someone was specifically looking for a connection between Pithos and Pandora and had blowfish key and the TLS fingerprint they really couldn't snoop?

**Comment by ClashTheBunny** [comment]
I just tried on android, and it works.  Here is the section of the Kodi log on Ubuntu Wily:
```
16:06:19 T:140546043705344   DEBUG: OnKey: return (0xf00d) pressed, action is Select
16:06:19 T:140546043705344   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.audio.pandoki/)
16:06:19 T:140546043705344   DEBUG:   ParentPath = [addons://sources/audio/]
16:06:19 T:140545181091584   DEBUG: StartScript - calling plugin Pandoki('plugin://plugin.audio.pandoki/','2','')
16:06:19 T:140545181091584   DEBUG: WaitOnScriptResult - waiting on the Pandoki (id=2) plugin...
16:06:19 T:140544172861184  NOTICE: Thread LanguageInvoker start, auto delete: false
16:06:19 T:140544172861184    INFO: initializing python engine.
16:06:19 T:140544172861184   DEBUG: CPythonInvoker(2, /tank/rmason/.kodi/addons/plugin.audio.pandoki/default.py): start processing
16:06:19 T:140544172861184  NOTICE: -->Python Interpreter Initialized<--
16:06:19 T:140544172861184   DEBUG: CPythonInvoker(2, /tank/rmason/.kodi/addons/plugin.audio.pandoki/default.py): the source file to load is "/tank/rmason/.kodi/addons/plugin.audio.pandoki/default.py"
16:06:19 T:140544172861184   DEBUG: CPythonInvoker(2, /tank/rmason/.kodi/addons/plugin.audio.pandoki/default.py): setting the Python path to /tank/rmason/.kodi/addons/plugin.audio.pandoki:/tank/rmason/.kodi/addons/script.module.mutagen/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/tank/rmason/.local/lib/python2.7/site-packages:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gst-0.10:/usr/lib/python2.7/dist-packages/gtk-2.0:/usr/lib/pymodules/python2.7:/usr/lib/python2.7/dist-packages/ubuntu-sso-client
16:06:19 T:140544172861184   DEBUG: CPythonInvoker(2, /tank/rmason/.kodi/addons/plugin.audio.pandoki/default.py): entering source directory /tank/rmason/.kodi/addons/plugin.audio.pandoki
16:06:19 T:140544172861184   DEBUG: CPythonInvoker(2, /tank/rmason/.kodi/addons/plugin.audio.pandoki/default.py): instantiating addon using automatically obtained id of "plugin.audio.pandoki" dependent on version 2.1.0 of the xbmc.python api
16:06:20 T:140546043705344   DEBUG: ------ Window Init (DialogBusy.xml) ------
16:06:20 T:140546043705344   DEBUG: Keyboard: scancode: 0x85, sym: 0x0137, unicode: 0x0000, modifier: 0x0
16:06:20 T:140546043705344   DEBUG: OnKey: leftwindows (0xf0d6) pressed, action is
16:06:28 T:140544172861184   ERROR: ERROR:root:Network error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
16:06:28 T:140544172861184  NOTICE: .
16:06:28 T:140544172861184  NOTICE: plugin.audio.pandoki Auth BAD
16:06:28 T:140546043705344   DEBUG: ------ Window Init (DialogYesNo.xml) ------
```

And here it is on Android Marshmallow:
```
16:11:45 T:18446744071974082864  NOTICE: -->Python Interpreter Initialized<--
16:11:45 T:18446744071974082864   DEBUG: CPythonInvoker(1, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.audio.pandoki/default.py): the source file to load is "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.audio.pandoki/default.py"
16:11:45 T:18446744071974082864   DEBUG: CPythonInvoker(1, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.audio.pandoki/default.py): setting the Python path to /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.audio.pandoki:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.mutagen/lib:/:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python26.zip:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python2.6:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python2.6/plat-linux3:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python2.6/lib-tk:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python2.6/lib-old:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python2.6/lib-dynload
16:11:45 T:18446744071974082864   DEBUG: CPythonInvoker(1, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.audio.pandoki/default.py): entering source directory /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.audio.pandoki
16:11:45 T:18446744071974082864   DEBUG: CPythonInvoker(1, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.audio.pandoki/default.py): instantiating addon using automatically obtained id of "plugin.audio.pandoki" dependent on version 2.1.0 of the xbmc.python api
16:12:01 T:18446744071974082864  NOTICE: plugin.audio.pandoki Auth  OK
16:12:05 T:18446744071974082864  NOTICE: plugin.audio.pandoki Dir   OK    1
```

These both happened from the same network at, as the logs say, about the same time.

**Comment by trevnorris** [comment]
Just a side note. This is not Ubuntu 15.10 specific. I'm running Xubuntu 15.04 3.19.0-32-generic x86_64. Receiving the same error `(_ssl.c:600)`.

**Comment by TingPing** [comment]
The cause of the problem is already known as mentioned in the first reply so more details are not needed everyone.

**Comment by alexhenrie** [comment]
I was able to work around this on Arch Linux by manually installing the intermediate certificate:
```
sudo wget https://knowledge.symantec.com/library/VERISIGN/ALL_OTHER/KB_IMAGES/SO26896/Cert_Files/VeriSign%20Class%203%20International%20Server%20CA%20-%20G3.cer -P /etc/ca-certificates/trust-source/anchors/ && sudo trust extract-compat
```
See https://www.archlinux.org/news/ca-certificates-update/

**Comment by aensley** [comment]
Thank you @alexhenrie! I was able to do the same on Ubuntu with:

```
if [ ! -d /usr/share/ca-certificates/extra/ ]; then sudo mkdir /usr/share/ca-certificates/extra/; fi
sudo wget https://knowledge.symantec.com/library/VERISIGN/ALL_OTHER/KB_IMAGES/SO26896/Cert_Files/VeriSign%20Class%203%20International%20Server%20CA%20-%20G3.cer -O /usr/share/ca-certificates/extra/Verisign_Class_3_International_Server_CA_-_G3.crt
sudo dpkg-reconfigure ca-certificates
```

I chose the interactive mode for installing new certificates when prompted and made sure `Verisign_Class_3_International_Server_CA_-_G3.crt` was selected.

Pithos works again!

**Comment by sirhc** [comment]
Similarly, on Fedora:

```
sudo wget https://knowledge.symantec.com/library/VERISIGN/ALL_OTHER/KB_IMAGES/SO26896/Cert_Files/VeriSign%20Class%203%20International%20Server%20CA%20-%20G3.cer -O /etc/pki/ca-trust/source/anchors/Verisign_Class_3_International_Server_CA_-_G3.crt
sudo update-ca-trust
```

**Comment by quicksketch** [comment]
Thanks @TingPing!

**Comment by mbott001** [comment]
On 11/24/2015 01:42, Nate Haug wrote:
>
> Thanks @TingPing <https://github.com/TingPing>!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pithos/pithos/issues/251#issuecomment-159170941>.
>
I'm not the sharpest crayon on the box, but I prefer to install from the 
ppa rather than via the software manager. In attempting to do so this 
morning, I've encountered what I think may be issues that I do not 
remember encountering before. Are they issues? Suggestions?

Thanks!

-- 
Mike

mbott@mlaptop:~$ sudo apt-get update
Ign http://dl.google.com stable InRelease
Get:1 http://security.ubuntu.com wily-security InRelease [64.4 kB]
Hit http://us.archive.ubuntu.com wily InRelease
Get:2 http://dl.google.com stable Release.gpg [198 B]
Get:3 http://us.archive.ubuntu.com wily-updates InRelease [64.4 kB]
Get:4 http://dl.google.com stable Release [1,347 B]
Ign http://ppa.launchpad.net wily InRelease
Get:5 http://security.ubuntu.com wily-security/main Sources [16.6 kB]
Get:6 http://dl.google.com stable/main amd64 Packages [1,217 B]
Get:7 http://security.ubuntu.com wily-security/restricted Sources [2,854 B]
Get:8 http://dl.google.com stable/main i386 Packages [1,209 B]
Get:9 http://us.archive.ubuntu.com wily-backports InRelease [64.5 kB]
Get:10 http://security.ubuntu.com wily-security/universe Sources [3,691 B]
Ign http://ppa.launchpad.net wily Release.gpg
Get:11 http://security.ubuntu.com wily-security/multiverse Sources [1,922 B]
Hit http://us.archive.ubuntu.com wily/main Sources
Hit http://us.archive.ubuntu.com wily/restricted Sources
Get:12 http://security.ubuntu.com wily-security/main amd64 Packages 
[42.3 kB]
Ign http://ppa.launchpad.net wily Release
Get:13 http://security.ubuntu.com wily-security/restricted amd64 
Packages [10.9 kB]
Hit http://us.archive.ubuntu.com wily/universe Sources
Get:14 http://security.ubuntu.com wily-security/universe amd64 Packages 
[24.8 kB]
Get:15 http://security.ubuntu.com wily-security/multiverse amd64 
Packages [5,859 B]
Hit http://us.archive.ubuntu.com wily/multiverse Sources
Get:16 http://security.ubuntu.com wily-security/main i386 Packages [41.5 kB]
Get:17 http://security.ubuntu.com wily-security/restricted i386 Packages 
[10.8 kB]
Hit http://us.archive.ubuntu.com wily/main amd64 Packages
Get:18 http://security.ubuntu.com wily-security/universe i386 Packages 
[24.8 kB]
Hit http://us.archive.ubuntu.com wily/restricted amd64 Packages
Get:19 http://security.ubuntu.com wily-security/multiverse i386 Packages 
[6,052 B]
Ign http://dl.google.com stable/main Translation-en_US
Hit http://us.archive.ubuntu.com wily/universe amd64 Packages
Get:20 http://security.ubuntu.com wily-security/main Translation-en 
[22.2 kB]
Hit http://us.archive.ubuntu.com wily/multiverse amd64 Packages
Ign http://dl.google.com stable/main Translation-en
Get:21 http://security.ubuntu.com wily-security/multiverse 
Translation-en [2,536 B]
Hit http://us.archive.ubuntu.com wily/main i386 Packages
Get:22 http://security.ubuntu.com wily-security/restricted 
Translation-en [2,666 B]
Hit http://us.archive.ubuntu.com wily/restricted i386 Packages
Get:23 http://security.ubuntu.com wily-security/universe Translation-en 
[15.2 kB]
Hit http://us.archive.ubuntu.com wily/universe i386 Packages
Hit http://us.archive.ubuntu.com wily/multiverse i386 Packages
Hit http://us.archive.ubuntu.com wily/main Translation-en
Hit http://us.archive.ubuntu.com wily/multiverse Translation-en
Hit http://us.archive.ubuntu.com wily/restricted Translation-en
Hit http://us.archive.ubuntu.com wily/universe Translation-en
Get:24 http://us.archive.ubuntu.com wily-updates/main Sources [24.1 kB]
Get:25 http://us.archive.ubuntu.com wily-updates/restricted Sources 
[3,741 B]
Get:26 http://us.archive.ubuntu.com wily-updates/universe Sources [6,112 B]
Get:27 http://us.archive.ubuntu.com wily-updates/multiverse Sources 
[1,922 B]
Get:28 http://us.archive.ubuntu.com wily-updates/main amd64 Packages 
[60.6 kB]
Get:29 http://us.archive.ubuntu.com wily-updates/restricted amd64 
Packages [13.3 kB]
Get:30 http://us.archive.ubuntu.com wily-updates/universe amd64 Packages 
[31.0 kB]
Get:31 http://us.archive.ubuntu.com wily-updates/multiverse amd64 
Packages [5,859 B]
Get:32 http://us.archive.ubuntu.com wily-updates/main i386 Packages 
[59.2 kB]
Get:33 http://us.archive.ubuntu.com wily-updates/restricted i386 
Packages [13.4 kB]
Get:34 http://us.archive.ubuntu.com wily-updates/universe i386 Packages 
[31.0 kB]
Get:35 http://us.archive.ubuntu.com wily-updates/multiverse i386 
Packages [6,052 B]
Get:36 http://us.archive.ubuntu.com wily-updates/main Translation-en 
[30.3 kB]
Get:37 http://us.archive.ubuntu.com wily-updates/multiverse 
Translation-en [2,536 B]
Get:38 http://us.archive.ubuntu.com wily-updates/restricted 
Translation-en [3,024 B]
Get:39 http://us.archive.ubuntu.com wily-updates/universe Translation-en 
[18.5 kB]
Get:40 http://us.archive.ubuntu.com wily-backports/main Sources [750 B]
Get:41 http://us.archive.ubuntu.com wily-backports/restricted Sources [28 B]
Get:42 http://us.archive.ubuntu.com wily-backports/universe Sources [833 B]
Err http://ppa.launchpad.net wily/main amd64 Packages
404 Not Found
Get:43 http://us.archive.ubuntu.com wily-backports/multiverse Sources [28 B]
Get:44 http://us.archive.ubuntu.com wily-backports/main amd64 Packages 
[606 B]
Err http://ppa.launchpad.net wily/main i386 Packages
404 Not Found
Get:45 http://us.archive.ubuntu.com wily-backports/restricted amd64 
Packages [28 B]
Get:46 http://us.archive.ubuntu.com wily-backports/universe amd64 
Packages [717 B]
Ign http://ppa.launchpad.net wily/main Translation-en_US
Get:47 http://us.archive.ubuntu.com wily-backports/multiverse amd64 
Packages [28 B]
Get:48 http://us.archive.ubuntu.com wily-backports/main i386 Packages 
[606 B]
Get:49 http://us.archive.ubuntu.com wily-backports/restricted i386 
Packages [28 B]
Get:50 http://us.archive.ubuntu.com wily-backports/universe i386 
Packages [714 B]
Get:51 http://us.archive.ubuntu.com wily-backports/multiverse i386 
Packages [28 B]
Ign http://ppa.launchpad.net wily/main Translation-en
Get:52 http://us.archive.ubuntu.com wily-backports/main Translation-en 
[486 B]
Get:53 http://us.archive.ubuntu.com wily-backports/multiverse 
Translation-en [28 B]
Get:54 http://us.archive.ubuntu.com wily-backports/restricted 
Translation-en [28 B]
Get:55 http://us.archive.ubuntu.com wily-backports/universe 
Translation-en [270 B]
Fetched 748 kB in 6s (116 kB/s)
W: Failed to fetch 
http://ppa.launchpad.net/pithos/ppa/ubuntu/dists/wily/main/binary-amd64/Packages 
404 Not Found

W: Failed to fetch 
http://ppa.launchpad.net/pithos/ppa/ubuntu/dists/wily/main/binary-i386/Packages 
404 Not Found

E: Some index files failed to download. They have been ignored, or old 
ones used instead.

**Comment by JasonLG1979** [comment]
> I'm not the sharpest crayon on the box, but I prefer to install from the
> ppa rather than via the software manager. In attempting to do so this
> morning, I've encountered what I think may be issues that I do not
> remember encountering before. Are they issues? Suggestions?

Nothing to do with this bug.
The PPA doesn't have a package for wily(15.10) for some reason. @TingPing?
Until the PPA is updated. You'll have to install from source if you want the latest version. Or you can use the vivid package.

**Comment by TingPing** [comment]
Would have to talk to @gregsheremeta about the PPA, he hasn't been active lately so I presume he is busy.
